name: DHD

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: Which repo to dust

jobs:
  gen_mat:
    runs-on: ubuntu-latest
    outputs: 
      assignments: ${{ steps.assign.outputs.assignments }}
    steps:
      - id: assign
        run: |
          echo "::set-output name=assignments::$(skopeo inspect docker://${{ github.event.inputs.repository }} | jq -c '[.RepoTags | _nwise(100) | tostring]')"
      
  pull:
    runs-on: ubuntu-latest
    needs: gen_mat
    strategy:
      matrix:
        tags: ${{ fromJSON(needs.gen_mat.outputs.assignments) }}
    env:
      TAGS: ${{ matrix.tags }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          n="$(echo "${TAGS}" | jq length)"
          i=0
          for tag in $(echo "${TAGS}" | jq -r '.[]'); do
            ((++i))
            echo "Processing ${i}/${n}"
            docker pull "${{github.event.inputs.repository }}:$tag"
            docker rmi -f "${{github.event.inputs.repository }}:$tag"
          done
